# Generated by Django 2.0.4 on 2018-04-19 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20180419_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_people',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
