# Generated by Django 2.0.4 on 2018-04-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('read_recoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Read_Num',
            new_name='ReadNum',
        ),
    ]
